security:
    providers:
        in_memory:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            stateless: true
            custom_authenticators:
                - App\Security\BearerTokenAuthenticator

    access_control:
        - { path: ^/up$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
